# publish to NPM Packages when a release is created

name: npm-publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish --tag js-upload-file
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}